"""initial db

Revision ID: cd48e3b8b30a
Revises: 
Create Date: 2020-10-29 09:24:18.672296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd48e3b8b30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlalchemy_app_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlalchemy_app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sqlalchemy_app_user_email'), 'sqlalchemy_app_user', ['email'], unique=True)
    op.create_index(op.f('ix_sqlalchemy_app_user_username'), 'sqlalchemy_app_user', ['username'], unique=True)
    op.create_table('sqlalchemy_app_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['sqlalchemy_app_city.id'], ),
    sa.ForeignKeyConstraint(['create_user_id'], ['sqlalchemy_app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sqlalchemy_app_teams_create_timestamp'), 'sqlalchemy_app_teams', ['create_timestamp'], unique=False)
    op.create_table('sqlalchemy_app_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['sqlalchemy_app_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlalchemy_app_players')
    op.drop_index(op.f('ix_sqlalchemy_app_teams_create_timestamp'), table_name='sqlalchemy_app_teams')
    op.drop_table('sqlalchemy_app_teams')
    op.drop_index(op.f('ix_sqlalchemy_app_user_username'), table_name='sqlalchemy_app_user')
    op.drop_index(op.f('ix_sqlalchemy_app_user_email'), table_name='sqlalchemy_app_user')
    op.drop_table('sqlalchemy_app_user')
    op.drop_table('sqlalchemy_app_city')
    # ### end Alembic commands ###
