"""added Game Model

Revision ID: f52f939a07e2
Revises: f3fd9dde6908
Create Date: 2021-03-21 21:28:31.570124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52f939a07e2'
down_revision = 'f3fd9dde6908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlalchemy_app_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hometeam_id', sa.Integer(), nullable=False),
    sa.Column('visitorteam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(length=24), nullable=False),
    sa.Column('playDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['hometeam_id'], ['sqlalchemy_app_teams.id'], ),
    sa.ForeignKeyConstraint(['visitorteam_id'], ['sqlalchemy_app_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sqlalchemy_app_games_playDate'), 'sqlalchemy_app_games', ['playDate'], unique=False)
    op.alter_column('sqlalchemy_app_players', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sqlalchemy_app_players', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_sqlalchemy_app_games_playDate'), table_name='sqlalchemy_app_games')
    op.drop_table('sqlalchemy_app_games')
    # ### end Alembic commands ###
