"""added followers

Revision ID: f537428081d4
Revises: cd48e3b8b30a
Create Date: 2021-03-20 20:56:13.848300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f537428081d4'
down_revision = 'cd48e3b8b30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['sqlalchemy_app_teams.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['sqlalchemy_app_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
